# Part 1

作業目標:<br>
在array中，可以靈活應用索引幫助資料擷取<br>
作業重點:<br>
陣列的索引、切片、以及屬性，皆需要注意使用方式<br>
陣列之中索引式由0開始請同學注意

題目:<br>
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。<br>
2.呈上題，將以上數列取出偶數。<br>
3.呈1題，將數列取出3的倍數。<br>

In [1]:
import numpy as np

In [2]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
a = np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [3]:
#2.呈上題，將以上數列取出偶數。
a[2::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
#3.呈1題，將數列取出3的倍數。
a[3::3]

array([ 3,  6,  9, 12, 15, 18])

# Part 2

# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


答: <br>
若a為多層次矩陣list(a)僅會將第一層轉換為list,其內部則仍為array <br>
使用tolist()則會讓所有array皆轉換成list

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [5]:
# 記得先 Import 正確的套件

'''
Your Code
'''

'\nYour Code\n'

In [6]:

a = np.random.randint(10, size=6) 

'''
Your Code
'''
print(a)
print(a.ndim)
print('透過a.dim = 1 我們可以得知a 為一維矩陣')

[8 2 6 0 7 3]
1
透過a.dim = 1 我們可以得知a 為一維矩陣


In [7]:
b = np.random.randint(10, size=(3,4)) 

'''
Your Code
'''
print(b)
print(b.ndim)
print(b.shape)
print('透過b.dim = 2 我們可以得知b 為二維矩陣')
print('另外透過b.shape = (3,4)我們可以得知b為3列4行的矩陣')

[[8 0 4 4]
 [3 9 5 0]
 [3 8 3 1]]
2
(3, 4)
透過b.dim = 2 我們可以得知b 為二維矩陣
另外透過b.shape = (3,4)我們可以得知b為3列4行的矩陣


In [8]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(c.dtype)
print(c.itemsize)
print("透過itemsize我們可以得知c矩陣每一個元素的大小(byte單位)")

[[[2 3]
  [2 4]
  [9 7]]

 [[3 4]
  [1 0]
  [3 5]]]
int32
4
透過itemsize我們可以得知c矩陣每一個元素的大小(byte單位)


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [9]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[5, 9, 2, 8, 7, 6]
[5, 9, 2, 8, 7, 6]


In [10]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[7, 2, 0, 2], [4, 3, 4, 8], [0, 2, 5, 0]]
[array([7, 2, 0, 2]), array([4, 3, 4, 8]), array([0, 2, 5, 0])]


In [11]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[2, 2], [2, 4], [3, 8]], [[9, 6], [7, 3], [9, 0]]]
[array([[2, 2],
       [2, 4],
       [3, 8]]), array([[9, 6],
       [7, 3],
       [9, 0]])]


In [31]:
def tolist(iterable):
    print(iterable.shape)
    return list(iterable)
print(tolist(a))
print(tolist(b))
print(tolist(c))

(6,)
[5, 9, 2, 8, 7, 6]
(3, 4)
[array([7, 2, 0, 2]), array([4, 3, 4, 8]), array([0, 2, 5, 0])]
(2, 3, 2)
[array([[2, 2],
       [2, 4],
       [3, 8]]), array([[9, 6],
       [7, 3],
       [9, 0]])]
