## Basic

# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```


In [1]:
import numpy as np

In [2]:
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

In [3]:
print(a + a) #[40,60,80,100]
print(a + b) #[21,32,43,54]
print(a + c) #[21,31,41,51]
print(a + d) #[21,31,41,51]
print(a + e) #[21,32,41,52]

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


In [4]:
# 記得先 Import 正確的套件

import numpy as np


In [5]:
A = np.ones(3)*1
B = np.ones(3)*2

'''
Your Code
'''
# without loops
(A+B)*(-A/2)

array([-1.5, -1.5, -1.5])

In [6]:
#with loop

for i,a in enumerate(A):
    A[i] = (a+ B[i])*(-a/2)
print(A)

[-1.5 -1.5 -1.5]


### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


In [7]:
A = np.ones((1,6))
B = np.ones((6,1))

'''
Your Code
'''

'\nYour Code\n'

In [8]:
A = np.ones((1,6))
B = np.ones((6,1))
print(A)
print(B)

[[1. 1. 1. 1. 1. 1.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [9]:
#內積
print(np.dot(A,B))

[[6.]]


In [10]:
#外積
print(np.cross(A,B))

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [11]:
# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```




### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


A = np.ones(3)*1
B = np.ones(3)*2

print((A + B) * (-A / 2))

### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


# 記得先 Import 正確的套件

import numpy as np


# 參考解答

A = np.ones((1,6))
B = np.ones((6,1))

print(A * B)
print(A @ B)





SyntaxError: invalid character in identifier (<ipython-input-11-4f91b34da81b>, line 3)

## Extension

作業目標:<br>
嘗試練習log的函式並應用<br>
作業重點:<br>
學員需要複習log的轉換方式<br>
熟悉運用指數函數以及對數函數

題目:<br>
運用投影片中的分貝公式回答下列問題。<br>
1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?<br>
2.30分貝的聲壓會是50分貝的幾倍?


In [ ]:
import numpy as np 

In [12]:
#1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
#請寫下程式
V1 = 20000
V0 = 20
20 * np.log10(V1/V0)

60.0

In [ ]:
#2.30分貝的聲壓會是50分貝的幾倍?
#公式移項過後可以得到 V1 = ?
#請寫下程式


In [13]:
b50 = 10 ** (50/20 + np.log10(V0))

In [14]:
b50

6324.55532033676