# Part 1

作業目標<br>
在一個陣列中放入多屬性陣列，進一步對陣列做運算<br>
作業重點<br>
在建立結構化陣列前需要先設定屬性，在做運算時須注意資料屬性

題目:<br>
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']<br>
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']<br>
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]<br>
rank_list = [8,1,5,4,7,6,2,3]<br>
myopia_list = [True,True,False,False,True,True,False,False]<br>
1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]<br>
2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重
3. 呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重


In [1]:
import numpy as np 

In [2]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

In [3]:
#1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]

In [4]:
dt = np.dtype({'names':('name', 'sex', 'weight', 'rank',"myopia"), 'formats':('U4', 'U4', np.float32,np.int32, '?')})

In [5]:
stats = np.zeros(8, dtype = dt)

In [6]:
stats['name'] = name_list
stats['sex'] = sex_list
stats['weight'] = weight_list
stats['rank'] = rank_list
stats['myopia'] = myopia_list
stats

array([('小明', 'boy', 67.5, 8,  True), ('小華', 'boy', 75.3, 1,  True),
       ('小菁', 'girl', 50.1, 5, False), ('小美', 'girl', 45.5, 4, False),
       ('小張', 'boy', 80.8, 7,  True), ('John', 'boy', 90.4, 6,  True),
       ('Mark', 'boy', 78.4, 2, False), ('Tom', 'boy', 70.7, 3, False)],
      dtype=[('name', '<U4'), ('sex', '<U4'), ('weight', '<f4'), ('rank', '<i4'), ('myopia', '?')])

In [7]:
#2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重

In [8]:
sum(stats['weight'])/len(stats['weight'])

69.83750057220459

In [9]:
# standard answer
np.mean(stats["weight"])

69.8375

In [10]:
#3. 呈上題，進一步算出男生(sex欄位是boy)平均體重

In [11]:
sum(stats[stats["sex"]== 'boy']['weight'])/len(stats[stats["sex"]== 'boy'])

77.18333435058594

In [12]:
# standard answer
boy_index = np.where(stats['sex']=='boy')[0]
np.mean(stats['weight'][boy_index])

77.18333

In [13]:
#3. 呈上題，進一步算出女生(sex欄位是girl)平均體重

In [14]:
sum(stats[stats["sex"]== 'girl']['weight'])/len(stats[stats["sex"]== 'girl'])

47.79999923706055

In [15]:
#standard answer
girl_index = np.where(stats['sex']=='girl')[0]
np.mean(stats['weight'][girl_index])

47.8

# Part 2

# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


### Ans:
np.zeros 會自動生成一個所有元素原始值皆為0的矩陣。<br>
np.empty 則是會根據記憶體狀態隨機生成個元素的狀態<br>
以使用情境作分別的話，如果重視的是 **矩陣的形狀**而原始值並不重要的狀況下，np.empty會稍快<br>
但是若除了形狀以外也重視原始值，也就是說若要皆為0的話，np.zeros無論是在輸入/設定上或是運行速度都會勝過np.empty<br>
source1: https://stackoverflow.com/questions/26213199/np-fullsize-0-vs-np-zerossize-vs-np-empty <br>
source2: https://datascience.stackexchange.com/questions/52190/what-is-difference-between-np-zeros-and-np-empty <br>

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [16]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

In [17]:
# 參考解答

a = np.random.rand(2, 3)

'''
Your Code
'''
# dt2 = dtype(int)
print("before change: ",a)
print("after change: ", a.astype(int) )

before change:  [[0.25828617 0.55108246 0.35708033]
 [0.67377984 0.96635457 0.08093182]]
after change:  [[0 0 0]
 [0 0 0]]


In [18]:
#standard answer

print(a.round())
print(np.round(a))

[[0. 1. 0.]
 [1. 1. 0.]]
[[0. 1. 0.]
 [1. 1. 0.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [19]:
m = 20
n = 40

'''
Your Code
'''
np.reshape(np.linspace(20,40,6),(2,3))

array([[20., 24., 28.],
       [32., 36., 40.]])

In [24]:
#standard answer
a = np.random.rand(2, 3) * (n - m)
b = a
print(a)
print(b)
print( b % 1) # a(b) 的小數部分
#故: a-b%1 會轉為整數
print((a - b % 1) + m)

[[13.78717577  9.89801096 18.5261134 ]
 [ 5.88125079  6.78042648  9.71973512]]
[[13.78717577  9.89801096 18.5261134 ]
 [ 5.88125079  6.78042648  9.71973512]]
[[0.78717577 0.89801096 0.5261134 ]
 [0.88125079 0.78042648 0.71973512]]
[[33. 29. 38.]
 [25. 26. 29.]]
