# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [16]:
'''
Your Code
'''
import numpy as np
a = np.array([[6, 9, 6],
           [1, 1, 2]])
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 

# a.sum() , np.sum(a) 回傳所有加總的值
# sum(a) 回傳軸的加總後的陣列

25
25
[ 7 10  8]


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [17]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

In [22]:
A = np.random.random((5, 5))

print(A)

B = A/np.linalg.norm(A)
print(B)

[[0.81481404 0.51180207 0.13652826 0.99886297 0.70646159]
 [0.98225175 0.07794318 0.02732663 0.26164252 0.34136742]
 [0.73412198 0.86725743 0.43697157 0.59674047 0.06598198]
 [0.53553503 0.91327482 0.48854372 0.92027282 0.67922488]
 [0.36771964 0.70594913 0.51220715 0.55279441 0.72184551]]
[[0.25987491 0.16323297 0.04354401 0.31857505 0.22531723]
 [0.3132771  0.02485902 0.00871549 0.08344766 0.10887494]
 [0.23413917 0.27660108 0.1393667  0.19032303 0.02104414]
 [0.1708023  0.29127776 0.15581501 0.29350969 0.21663041]
 [0.11727965 0.22515378 0.16336216 0.17630697 0.23022374]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [39]:
'''
Your Code
'''
np.random.seed(25)
a  = np.random.random(10)
a[[a == np.max(a)]] = -1
a

<ipython-input-39-2417b94b4ead>:6: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  a[[a == np.max(a)]] = -1


array([-1.        ,  0.58227693,  0.27883894,  0.18591123,  0.41110013,
        0.11737555,  0.68496874,  0.43761106,  0.55622933,  0.36708032])