# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
# 記得先 Import 正確的套件

import numpy as np
import random

In [2]:
random.seed(99)
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
Z

array([[[7, 9, 2, ..., 9, 9, 1],
        [2, 0, 1, ..., 1, 4, 5],
        [6, 2, 8, ..., 1, 3, 1],
        ...,
        [8, 7, 5, ..., 4, 9, 9],
        [3, 6, 5, ..., 9, 9, 5],
        [0, 0, 2, ..., 5, 9, 0]],

       [[3, 2, 8, ..., 8, 8, 3],
        [4, 5, 6, ..., 0, 7, 5],
        [4, 3, 7, ..., 7, 8, 2],
        ...,
        [7, 7, 6, ..., 8, 3, 6],
        [1, 0, 6, ..., 4, 6, 9],
        [1, 3, 7, ..., 9, 0, 4]],

       [[8, 8, 3, ..., 6, 2, 4],
        [4, 0, 1, ..., 5, 2, 2],
        [3, 1, 8, ..., 4, 9, 8],
        ...,
        [3, 0, 1, ..., 6, 3, 0],
        [5, 3, 8, ..., 0, 5, 0],
        [0, 7, 8, ..., 2, 8, 6]],

       ...,

       [[2, 0, 0, ..., 0, 3, 6],
        [7, 6, 6, ..., 4, 8, 6],
        [9, 6, 7, ..., 1, 0, 7],
        ...,
        [4, 1, 8, ..., 5, 9, 6],
        [7, 4, 9, ..., 5, 0, 5],
        [3, 7, 0, ..., 0, 6, 2]],

       [[7, 6, 0, ..., 6, 3, 6],
        [0, 6, 1, ..., 8, 8, 2],
        [7, 1, 2, ..., 5, 9, 1],
        ...,
        [7, 5, 9, ..., 

In [3]:
%timeit -n 10 a = 2

Z + 1

84.3 ns ± 23.8 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[ 8, 10,  3, ..., 10, 10,  2],
        [ 3,  1,  2, ...,  2,  5,  6],
        [ 7,  3,  9, ...,  2,  4,  2],
        ...,
        [ 9,  8,  6, ...,  5, 10, 10],
        [ 4,  7,  6, ..., 10, 10,  6],
        [ 1,  1,  3, ...,  6, 10,  1]],

       [[ 4,  3,  9, ...,  9,  9,  4],
        [ 5,  6,  7, ...,  1,  8,  6],
        [ 5,  4,  8, ...,  8,  9,  3],
        ...,
        [ 8,  8,  7, ...,  9,  4,  7],
        [ 2,  1,  7, ...,  5,  7, 10],
        [ 2,  4,  8, ..., 10,  1,  5]],

       [[ 9,  9,  4, ...,  7,  3,  5],
        [ 5,  1,  2, ...,  6,  3,  3],
        [ 4,  2,  9, ...,  5, 10,  9],
        ...,
        [ 4,  1,  2, ...,  7,  4,  1],
        [ 6,  4,  9, ...,  1,  6,  1],
        [ 1,  8,  9, ...,  3,  9,  7]],

       ...,

       [[ 3,  1,  1, ...,  1,  4,  7],
        [ 8,  7,  7, ...,  5,  9,  7],
        [10,  7,  8, ...,  2,  1,  8],
        ...,
        [ 5,  2,  9, ...,  6, 10,  7],
        [ 8,  5, 10, ...,  6,  1,  6],
        [ 4,  8,  1, ...,  1,  7

In [4]:
%timeit -n 10 a = 2

for row in Z:
    for r in row:
        for ele in r:
            ele = ele + 1
Z

184 ns ± 15.9 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[7, 9, 2, ..., 9, 9, 1],
        [2, 0, 1, ..., 1, 4, 5],
        [6, 2, 8, ..., 1, 3, 1],
        ...,
        [8, 7, 5, ..., 4, 9, 9],
        [3, 6, 5, ..., 9, 9, 5],
        [0, 0, 2, ..., 5, 9, 0]],

       [[3, 2, 8, ..., 8, 8, 3],
        [4, 5, 6, ..., 0, 7, 5],
        [4, 3, 7, ..., 7, 8, 2],
        ...,
        [7, 7, 6, ..., 8, 3, 6],
        [1, 0, 6, ..., 4, 6, 9],
        [1, 3, 7, ..., 9, 0, 4]],

       [[8, 8, 3, ..., 6, 2, 4],
        [4, 0, 1, ..., 5, 2, 2],
        [3, 1, 8, ..., 4, 9, 8],
        ...,
        [3, 0, 1, ..., 6, 3, 0],
        [5, 3, 8, ..., 0, 5, 0],
        [0, 7, 8, ..., 2, 8, 6]],

       ...,

       [[2, 0, 0, ..., 0, 3, 6],
        [7, 6, 6, ..., 4, 8, 6],
        [9, 6, 7, ..., 1, 0, 7],
        ...,
        [4, 1, 8, ..., 5, 9, 6],
        [7, 4, 9, ..., 5, 0, 5],
        [3, 7, 0, ..., 0, 6, 2]],

       [[7, 6, 0, ..., 6, 3, 6],
        [0, 6, 1, ..., 8, 8, 2],
        [7, 1, 2, ..., 5, 9, 1],
        ...,
        [7, 5, 9, ..., 

In [5]:
%timeit -n 10 a = 2
# type(np.array(np.nditer(Z)))
for d in np.array(np.nditer(Z)):
    d += 1

52.9 ns ± 12.8 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [6]:

Z = np.random.randint(0,10,50)
print(Z)


[6 6 5 5 0 9 7 8 5 1 2 6 3 2 8 7 9 1 7 2 3 1 8 5 9 2 8 6 3 0 1 8 0 9 1 1 0
 8 6 0 5 6 4 4 0 4 8 2 8 6]


In [7]:
rint = np.argmax(np.bincount(Z))
# bincount returns the times a number has appeared with the number as its index
# argmax returns the index of the largest value
rint

8

In [8]:
# from standard answer: "to find ALL the indexes"
np.where(Z == rint)[0]

array([ 7, 14, 22, 26, 31, 37, 46, 48], dtype=int64)

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [9]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[2, 6, 9, 5, 2, 7]
[2, 6, 9, 5, 2, 7]
[[8, 5, 2, 7], [7, 7, 2, 6], [2, 5, 3, 4]]
[array([8, 5, 2, 7]), array([7, 7, 2, 6]), array([2, 5, 3, 4])]
[[[6, 8], [4, 0], [5, 6]], [[5, 0], [4, 7], [9, 4]]]
[array([[6, 8],
       [4, 0],
       [5, 6]]), array([[5, 0],
       [4, 7],
       [9, 4]])]


In [10]:
def tolist(iterable):
    final_list = list()
    if type(iterable) != np.ndarray:
        return iterable
    else:
        for obj in iterable:
            final_list.append(tolist(obj))
    return iterable
        
print(tolist(a))
print(tolist(b))
print(tolist(c))

[2 6 9 5 2 7]
[[8 5 2 7]
 [7 7 2 6]
 [2 5 3 4]]
[[[6 8]
  [4 0]
  [5 6]]

 [[5 0]
  [4 7]
  [9 4]]]
